# Generated by Django 3.0.2 on 2020-03-20 12:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('tr', 'Turkish'), ('kiny', 'Kinyarwanda')], default='English', max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unmentioned', 'Unmentioned')], default='Unmentioned', max_length=15, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('birthday', models.DateField(null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('career', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Unmentioned', 'Unmentioned')], default='Unmentioned', max_length=100)),
                ('profile_pic', models.ImageField(default='media/profile_pics/Noprofile.PNG', upload_to='media/profile_pics')),
                ('Channel_owner', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('language', models.CharField(default='English', max_length=10)),
                ('privacy', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=8)),
                ('date_created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Profile')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('time_sent', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('seen', models.BooleanField(default=False)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='English', max_length=10)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('privacy', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=8)),
                ('date_created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Profile')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
