# Generated by Django 3.0.2 on 2020-03-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_time']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='time_sent',
            new_name='date_time',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow')], default='Like', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='to_channel',
            field=models.BooleanField(default=False),
        ),
    ]
