# Generated by Django 3.0.2 on 2020-03-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
