# Generated by Django 3.0.2 on 2020-03-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20200323_2209'),
        ('Channel', '0002_auto_20200320_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_submitted']},
        ),
        migrations.RenameField(
            model_name='channeladmin',
            old_name='notification',
            new_name='is_notified',
        ),
        migrations.AddField(
            model_name='channel',
            name='languages',
            field=models.ManyToManyField(to='Main.ChannelLanguage'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='bio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
