# Generated by Django 3.0.2 on 2020-03-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20200323_2209'),
        ('Channel', '0003_auto_20200323_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeladmin',
            name='confirm_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='languages',
            field=models.ManyToManyField(to='Main.Language'),
        ),
    ]
