# Generated by Django 3.0.2 on 2020-03-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20200323_2243'),
        ('Channel', '0004_auto_20200323_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='languages',
            field=models.ManyToManyField(blank=True, to='Main.Language'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='website',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
