# Generated by Django 3.0.2 on 2020-03-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20200328_1814'),
        ('Channel', '0005_auto_20200323_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeladmin',
            name='languages',
            field=models.ManyToManyField(blank=True, to='Main.Language'),
        ),
        migrations.AddField(
            model_name='topic',
            name='languages',
            field=models.ManyToManyField(blank=True, to='Main.Language'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
