# Generated by Django 3.0.2 on 2020-03-20 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 3, 20, 12, 55, 46, 928505))),
                ('error_type', models.TextField(choices=[('Timeout', 'Timeout'), ('Privacy Issue', 'Privacy')])),
                ('error_checked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(null=True)),
                ('posted_by', models.IntegerField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2020, 3, 20, 12, 55, 46, 929505, tzinfo=utc))),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Reported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
