# Generated by Django 3.0.2 on 2020-03-22 15:05

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20200320_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 15, 5, 29, 328835)),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 15, 5, 29, 332833, tzinfo=utc)),
        ),
    ]
