# Generated by Django 3.0.2 on 2020-03-23 19:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20200323_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='error',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 19, 9, 29, 731847)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 19, 9, 29, 735858, tzinfo=utc)),
        ),
    ]
