# Generated by Django 3.0.2 on 2020-03-23 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Channel', '0004_auto_20200323_2236'),
        ('Main', '0005_auto_20200323_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChannelLanguage',
        ),
        migrations.AddField(
            model_name='language',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='error',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 19, 35, 50, 456590)),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 19, 35, 50, 460589, tzinfo=utc)),
        ),
    ]
