# Generated by Django 3.0.2 on 2020-03-23 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20200323_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 19, 43, 8, 609110)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 19, 43, 8, 609110, tzinfo=utc)),
        ),
    ]
