# Generated by Django 3.0.2 on 2020-03-28 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20200323_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 15, 14, 6, 744120)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 15, 14, 6, 745121, tzinfo=utc)),
        ),
    ]
