# Generated by Django 3.0.2 on 2020-03-29 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20200328_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 8, 58, 50, 534567)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 8, 58, 50, 534567, tzinfo=utc)),
        ),
    ]
