# Generated by Django 3.0.2 on 2020-03-28 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_thumbnails'),
        ),
        migrations.CreateModel(
            name='UserGuideLanguageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='EN', max_length=10)),
                ('user_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='Business.UserGuide')),
            ],
        ),
    ]
